### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#13]
# Unofficial Technical Roadmap 
This is a rough technical roadmap of what needs build for our initial vision. Timeline is subject to change. Many of the items can be done in parallel. 

```mermaid
gantt
    title Unofficial Technical Roadmap
    dateFormat  YYYY-MM-DD
    excludes    weekends

axisFormat %b-%d
Secureum CAREX Report : milestone, m2, 2022-04-07, 0d
Audits Finished : milestone, m3, 2022-05-11, 0d
Testnet Ready : milestone, m4, 2022-05-13, 0d
Launch Week :milestone, m5, 2022-05-23, 0d


    section Frontend
    Core Page Design           :active, a1, 2022-04-01, 31d
    Auxiliary Page Design     :a2 ,2022-04-29, 3d
    section Smart Contracts
    Pre-audit fixes      :active, b1, 2022-04-07  , 7d

    section Audits
    Zellic          :c1, 2022-04-18, 5d
   Spearbit     :c2,  2022-05-02 , 7d

section Confrences
Permissionless :e1, 2022-05-16, 5d

 ```

## 0-3 Months (May mainnet launch internal goal) (July mainnet is public date) 
* [x] Branding, product, landing page designs: (ETA end of February) (handled by [VectorDAO](https://vectordao.com/))  
* [x] Landing page built (outsource?) @jordanalexandermeyer 
* [x] Subgraph built @RusseII @luckyrobot 
* [x]  V1 smart contracts developed - all functionality outlined in our [protocol spec](https://github.com/porter-finance/v1-core/blob/main/spec/overview.md) is implemented @Namaskar-1F64F 
* [x]  [Internal audit](https://www.auditless.com/codex/how-to-do-a-security-review) (Get help from Peteris and Stu?)  @RusseII  @Namaskar-1F64F @luckyrobot
* [x] Testnet testing
* [x] Make contracts public + add gitbook technical documentation @RusseII 
* [x]  Pre-Audit with Secureum CARE-X (March 24-31) @Namaskar-1F64F
* [x] External audit @RusseII with [Zellic](https://zellic.io) (~April 18th-April 22nd) 
* [x] Smart contracts finalized @Namaskar-1F64F  (April 17th) 
* [x] External audit @RusseII with [Spearbit](https://spearbit.com/) (~May 2th-May 11th) 
* [x] Core frontend pages release ready @luckyrobot 
* [x]  Immutify Bug Bounty @RusseII 
* [ ] V1 testnet release
* [ ] V1 mainnet release
* [ ] Auxiliary frontend pages built @luckyrobot  

## 3-6 Months 

**Explore governance** 

**Explore tokenomics** 
**Porter REFI** 

**Trading platform**
This will allows investors to trade their bonds which is one of the big value adds of bonds. They are liquid and tradable while loans are not. This is a high priority.

**Credit default swaps**
This will allow investors to hedge themselves when purchasing bonds

**Bond ratings on demand**
This will be helpful but Prime is working on this and it isn't a high priority.

**Backing debt with a lien on the treasury or project token mint function**
This will make debt much more trustless.

### Ideas
https://github.com/porter-finance/v1-core/issues/128
https://github.com/porter-finance/frontend-ido/issues/7

### Resources
https://a16z.com/2020/01/09/progressive-decentralization-crypto-product-management/
https://docs.porter.finance
